### ISSUE TITLE
Resync Deleted files not working

### ISSUE THREAD

**Issue by PixelPoxel** [readwiseio/obsidian-readwise#45]
I recently reorganised my vault, and reset the readwise sync in my vault i.e. deleted all the markdown files from readwise.

now when i try to resync the readwise highlights it only syncs the new files, old files are not getting synced.

i have the 'Resync deleted files' enabled, but only new highlights are getting synced.
<img width="1104" alt="image" src="https://github.com/readwiseio/obsidian-readwise/assets/132498914/3c856b54-79c3-49b1-bd2a-ec9fbf635027">

**Comment by franciscoj** [comment]
Having the exact same issue here.

I've tried disabling all the plugins but this one and also restarting obsidian without success.

What I have ended up doing that has mitigated this has been putting all the highlights into a single folder. Each time I want to resync I just remove the folder and then it works. Otherwise only the new content gets synced.

**Comment by tyler-dot-earth** [comment]
I believe #67 will fix this.
