### ISSUE TITLE
Sync highllights  from Supplemental Books too

### ISSUE THREAD

**Issue by radzio** [readwiseio/obsidian-readwise#9]
Would be great to add support for exporting highlights from supplemental books too (just like Readwise Mirror plugin)

![image](https://user-images.githubusercontent.com/469111/129622427-a905da99-62dd-4753-beee-772275097461.png)

**Comment by TristanH** [comment]
Hey @radzio, unfortunately we can't support the exporting of Supplemental highlights, due to copyright concerns :/ 

In fact, we probably shouldn't support them via API in the readwise-mirror extension either... may have to cut those from our API.

Sorry about that, we would love to support as many workflows as possible, but it's just not doable for us.

**Comment by radzio** [comment]
Ah that's sad but perfectly understandable 😞
